<a href="https://colab.research.google.com/github/GisangLee/deep_learning_network_calculation/blob/main/2_Artificial_Neurons.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Affine Functions with One Feature

### Weighted Sum

> z = xw
   - w : weight

> Weight는 input값에 곱해져 output을 변화시키는 존재

### Affine Transformation

> z = xw + b
  - input에 weight을 곱한 후 bias를 더해준다.

In [16]:
# Affine Functions with 1 Feature

import tensorflow as tf
from tensorflow.keras.layers import Dense

# input setting
# Input은 metric 형태로 만들어야한다.
x = tf.constant([[10.]])

# affine function
# Dense는 weigth, bias를 가지고 있다
dense = Dense(units=1, activation="linear")

# y값 연산
# forward propagation + params initialization
y_tf = dense(x)

# weight, bias 출력
W, B = dense.get_weights()

# forward propagation manullaly
y_man = tf.linalg.matmul(x, W) + B

print("======= Input/Weight/Bias ===========")
print(f"x : {x.shape}\n{x.numpy()}\n")
print(f"w : {W}\n b: {B}\n")

print(f"========= Output ==============")
print(f"y ( Tensorflow ) : {y_tf.shape}\n{y_tf.numpy()}\n")
print(f"y ( Manullaly ) : {y_man.shape}\n{y_man}\n")

======= Input/Weight/Bias ===========
x : (1, 1)
[[10.]]

w : [[1.5401791]]
 b: [0.]

========= Output ==============
y ( Tensorflow ) : (1, 1)
[[15.401792]]

y ( Manullaly ) : (1, 1)
[[15.401792]]



In [29]:
# Params Initialization

import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.initializers import Constant

x = tf.constant([[10.]])

# weight / bias
w, b = tf.constant(10.), tf.constant(20.)
w_init, b_init = Constant(w), Constant(b)


# affine functions
dense = Dense(
    units=1,
    activation="linear",
    kernel_initializer=w_init,
    bias_initializer=b_init
)

y_tf = dense(x)

W, B = dense.get_weights()

print(f"W : {W.shape}\n{W}\n")
print(f"B : {B.shape}\n{B}\n")

W : (1, 1)
[[10.]]

B : (1,)
[20.]



#### Affine Function with N Features

In [35]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

x = tf.random.uniform(shape=(1, 10), minval=0, maxval=10)


dense = Dense(
    units=1
)

y_tf = dense(x)

W, B = dense.get_weights()

# y_man = X^T * W + b = z
y_man = tf.linalg.matmul(x, W) + B

print("======= Input/Weight/Bias ===========")
print(f"x : {x.shape}\n{x.numpy()}\n")
print(f"w : {W.shape}\n{W}\n")
print(f"b : {B.shape}\n{B}\n")

print(f"========= Output ==============")
print(f"y ( Tensorflow ) : {y_tf.shape}\n{y_tf.numpy()}\n")
print(f"y ( Manullaly ) : {y_man.shape}\n{y_man}\n")

======= Input/Weight/Bias ===========
x : (1, 10)
[[5.8892846  0.912683   8.315819   9.8596945  0.37800908 4.2235146
  4.982388   4.770267   9.785839   3.5090756 ]]

w : (10, 1)
[[ 0.36639374]
 [ 0.17793477]
 [ 0.6316677 ]
 [ 0.07071316]
 [ 0.22269827]
 [-0.10401112]
 [ 0.3596707 ]
 [-0.3529274 ]
 [ 0.54569846]
 [-0.50378454]]

b : (1,)
[0.]

========= Output ==============
y ( Tensorflow ) : (1, 1)
[[11.595889]]

y ( Manullaly ) : (1, 1)
[[11.595889]]



## 2. Activation Functions

### Sigmoid

### Tanh

### ReLu

## 3. Artificial Neurons


- Affine Function + Activations Functions

In [43]:
# Activation Layers

import tensorflow as tensorflow
from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Activation

# input setting
x = tf.random.uniform(
    shape=(1, 5)
)

# activation function
sigmoid = Activation("sigmoid")
tanh = Activation("tanh")
relu = Activation("relu")

# forward propagation
y_sigmoid_tf = sigmoid(x)
y_tanh_tf = tanh(x)
y_relu_tf = relu(x)

# forward propagation manullaly
y_sigmoid_man = 1 / (1 + exp(-x))
y_tanh_man = (exp(x) - exp(-x)) / (exp(x) + exp(-x))
y_relu_man = maximum(x, 0)

print(f"x : {x.shape}\n{x}\n")
print(f" y ( Tensor sigmoid ) : {y_sigmoid_tf.shape}\n{y_sigmoid_tf.numpy()}\n")
print(f" y ( Manullaly sigmoid ) : {y_sigmoid_man.shape}\n{y_sigmoid_man}\n")

print(f" y ( Tensor tanh ) : {y_tanh_tf.shape}\n{y_tanh_tf.numpy()}\n")
print(f" y ( Manullaly tanh ) : {y_tanh_man.shape}\n{y_tanh_man}\n")

print(f" y ( Tensor relu ) : {y_relu_tf.shape}\n{y_relu_tf.numpy()}\n")
print(f" y ( Manullaly relu ) : {y_relu_man.shape}\n{y_relu_man}\n")

x : (1, 5)
[[0.3555894  0.56863    0.19730711 0.58163273 0.3465097 ]]

 y ( Tensor sigmoid ) : (1, 5)
[[0.58797234 0.638447   0.54916734 0.641443   0.58577096]]

 y ( Manullaly sigmoid ) : (1, 5)
[[0.5879723  0.638447   0.5491674  0.641443   0.58577096]]

 y ( Tensor tanh ) : (1, 5)
[[0.34132314 0.51435244 0.19478597 0.52385116 0.33327654]]

 y ( Manullaly tanh ) : (1, 5)
[[0.34132314 0.51435244 0.19478597 0.5238511  0.33327654]]

 y ( Tensor relu ) : (1, 5)
[[0.3555894  0.56863    0.19730711 0.58163273 0.3465097 ]]

 y ( Manullaly relu ) : (1, 5)
[[0.3555894  0.56863    0.19730711 0.58163273 0.3465097 ]]



In [54]:
# Activation in Dense Layer

import tensorflow as tf
from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Dense

# input setting
x = tf.random.uniform(
    shape=(1, 5)
)

# artificial neurons
dense_sigmoid = Dense(
    units=1,
    activation="sigmoid"
)

dense_tanh = Dense(
    units=1,
    activation="tanh"
)

dense_relu = Dense(
    units=1,
    activation="relu"
)


# forward propagation
y_sigmoid = dense_sigmoid(x)
y_tanh = dense_tanh(x)
y_relu = dense_relu(x)

print(f"AN with Sigmoid : {y_sigmoid.shape}\n{y_sigmoid.numpy()}\n")
print(f"AN with Tanh : {y_tanh.shape}\n{y_tanh.numpy()}\n")
print(f"AN with ReLu : {y_relu.shape}\n{y_relu.numpy()}\n")


# forward propagation manually
print("\n===========\n")
w, b = dense_sigmoid.get_weights()

z = tf.linalg.matmul(x, w) + b
a = 1 / (1 + exp(-z))

print(f"AN with Sigmoid man: {y_sigmoid.shape}\n{y_sigmoid.numpy()}\n")

AN with Sigmoid : (1, 1)
[[0.19723105]]

AN with Tanh : (1, 1)
[[-0.35695013]]

AN with ReLu : (1, 1)
[[0.69314903]]



AN with Sigmoid man: (1, 1)
[[0.19723105]]



In [57]:
# Minibatches

# Shapes of Dense Layer

import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 16, 10

x = tf.random.uniform(shape=(N, n_feature))

dense = Dense(
    units=1,
    activation="relu"
)

y = dense(x)
W, B = dense.get_weights()

print(f"shape of x : {x.shape}\n")
print(f"shape of W : {W.shape}\n")
print(f"shape of B : {B.shape}\n")

shape of x : (16, 10)

shape of W : (10, 1)

shape of B : (1,)



In [66]:
# Output Caculations

import tensorflow as tf
from tensorflow.math import exp
from tensorflow.keras.layers import Dense

N, n_feature = 16, 10
x = tf.random.uniform(shape=(N, n_feature))

dense = Dense(
    units=1,
    activation="sigmoid"
)

y_tf = dense(x) # forward propagation tf

W, B = dense.get_weights()

y_man = tf.linalg.matmul(x, W) + B # forward propagation manulally
y_man = 1 / ( 1 + exp(-y_man))

print(f"=========== Tensor Results ============")
print(f"{y_tf.numpy()}\n")
print(f"=========== Manulally Results ============")
print(f"{y_man.numpy()}\n")




=========== Tensor Results ============
[[0.84754556]
 [0.8233308 ]
 [0.7948987 ]
 [0.9204365 ]
 [0.9068081 ]
 [0.8899631 ]
 [0.8364588 ]
 [0.9111186 ]
 [0.8889987 ]
 [0.8899374 ]
 [0.868318  ]
 [0.8700981 ]
 [0.8198172 ]
 [0.90744567]
 [0.91196805]
 [0.85605943]]

=========== Manulally Results ============
[[0.8475456 ]
 [0.8233308 ]
 [0.7948986 ]
 [0.9204365 ]
 [0.906808  ]
 [0.8899631 ]
 [0.8364588 ]
 [0.9111186 ]
 [0.88899875]
 [0.8899374 ]
 [0.8683181 ]
 [0.8700981 ]
 [0.8198172 ]
 [0.9074456 ]
 [0.9119681 ]
 [0.8560594 ]]

